import type {
  ArchiveDocument,
  AudioRecord,
  CaseEnding,
  CaseMessage,
  LocationRecord,
  Person,
  TimelineEntry,
} from "@/types/case";

export const CASE_NUMBER = "P-07-0712";
export const INCIDENT_DATE = "2019.07.12";

export const people: Person[] = [
  {
    id: "lin-zhixia",
    name: "林知夏",
    role: "港口气象观测站实习员",
    ageAtIncident: 21,
    status: "失踪 / 法定状态不明",
    summary: "最后被记录于第七码头外侧通道。官方称她在暴雨中落水，但自动站没有记录到降雨。",
    statement: "她没有留下正式证词。笔记边缘反复写着：‘不要相信屏幕上的时间。’",
    linkedEvidence: ["ev-case-file", "ev-weather", "ev-phone", "ev-notebook"],
    secret: "她被陈牧从检修梯救起，此后以匿名委托人的身份追查栖潮计划；活下来并不意味着她已经摆脱监视。",
  },
  {
    id: "zhou-jiming",
    name: "周既明",
    role: "港务系统校时主管",
    ageAtIncident: 44,
    status: "三年前离职 / 去向不明",
    summary: "案发当夜拥有监控室和主时钟双重权限，是唯一能同时修改签到与录像时间的人。",
    statement: "‘零点以后我一直在北楼。那晚雨大，谁也没必要靠近七号泊位。’",
    linkedEvidence: ["ev-duty", "ev-offset", "ev-cctv", "ev-payment"],
    secret: "接受澜汐航运付款，将监控时间整体快调十一分钟，并补写不存在的值班员；他更像栖潮计划在雾港的执行负责人，而非唯一知情者。",
  },
  {
    id: "gu-weian",
    name: "顾惟安",
    role: "夜班调度员",
    ageAtIncident: 38,
    status: "仍在港务局任职",
    summary: "负责泊位闸门。他坚持当夜没有船只进入第七码头，却在纸本日志上留下了被擦除的压痕。",
    statement: "‘七号泊位封着。汽笛来自外海，我没看见白色船身。’",
    linkedEvidence: ["ev-port-log", "ev-photo", "ev-manifest", "ev-medical-context"],
    secret: "按周既明指令打开闸门，事后收到封口款；同期女儿的紧急治疗欠费被代缴。胁迫解释了他的选择，却不能洗掉开闸与作伪。",
  },
  {
    id: "xu-wancheng",
    name: "许晚澄",
    role: "气象站值班工程师",
    ageAtIncident: 31,
    status: "调任外港观测站",
    summary: "林知夏的带教。她签署了‘极端暴雨’补录单，却拒绝删除自动站原始缓存。",
    statement: "‘我按上级口径补录天气。原始仪器有没有故障，我不能断言。’",
    linkedEvidence: ["ev-weather", "ev-closure-order", "ev-notebook"],
    secret: "她保留无雨原始日志，并远程关闭自动报警节点，为林知夏争取了两分钟；她签下的假记录同时帮助了掩盖。",
  },
  {
    id: "chen-mu",
    name: "陈牧",
    role: "拖轮维修工",
    ageAtIncident: 52,
    status: "2020 年海上事故死亡",
    summary: "当夜值守检修艇。他的工具箱在七号泊位下层梯道被找到，证词却称自己从未离开船坞。",
    statement: "‘我只听见一声落水，雾太重，没看清人。’",
    linkedEvidence: ["ev-toolbox", "ev-photo", "ev-audio-0712"],
    secret: "从检修梯救起林知夏，并用物料艇把她送出港区。他后来的海上事故没有完整调查记录。",
  },
  {
    id: "tang-zhi",
    name: "唐芷",
    role: "《海岸线》调查记者",
    ageAtIncident: 29,
    status: "停刊后失联",
    summary: "曾因另一宗港区污染调查接触林知夏，也是最后通话的真实接听人。她在准备发表稿件后失联。",
    statement: "未留正式证词。未寄出的稿件标题是《没有下雨的溺亡夜》。",
    linkedEvidence: ["ev-phone", "ev-audio-0712", "ev-draft"],
    secret: "她将通话备份藏进旧式录音带，以摩斯码标注案件编号；为保护消息源，她主动改写了稿件中会暴露林知夏身份的细节。",
  },
  {
    id: "ye-lan",
    name: "叶澜",
    role: "档案记录中的临时值班员",
    ageAtIncident: 0,
    status: "查无此人",
    summary: "没有身份证号、工资记录或门禁卡实体，签名笔迹与周既明的校时单一致。",
    statement: "档案中只有一句事后代录：‘00:54，暴雨，实习员独自向外侧通道移动。’",
    linkedEvidence: ["ev-fake-clerk", "ev-duty", "ev-cctv"],
    secret: "周既明为封闭时间链而创建的虚构身份。",
  },
];

export const archiveDocuments: ArchiveDocument[] = [
  {
    id: "doc-case",
    code: "P-07-0712/A",
    title: "失踪事件结案摘要",
    category: "案情卷宗",
    date: "2019.07.16",
    author: "雾港港务局安保处",
    excerpt: "实习员于极端暴雨期间擅入封锁区域，推定夜间落水。",
    body: [
      "失踪者：林知夏，女，21 岁，气象观测站实习员。",
      "记录称 00:54 监控拍到其独自进入第七码头外侧通道。01:00 画面中断。",
      "搜救持续三十六小时，未发现遗体。鉴于当夜极端暴雨、海况恶劣，事件定性为意外落水。",
      "附注：所有涉及七号泊位的船舶记录不属于本案调查范围。",
      "归档口径：‘极端暴雨 / 无船靠泊 / 人员单独行动’。模板第四栏把‘泊位’误排成了‘泊 位’。",
      "系统元数据：封存指令草稿创建于 03:10，家属正式报案时间为 04:25。摘要没有解释结案口径为何先于报案出现。",
    ],
    evidenceId: "ev-case-file",
    secondRunNote: "二周目新增铅笔字：‘我看到你第二次打开它了，{{code}}。——知夏’",
  },
  {
    id: "doc-duty",
    code: "NIGHT/07-12",
    title: "夜班签到与校时表",
    category: "行政记录",
    date: "2019.07.12",
    author: "港务系统科",
    excerpt: "周既明于 00:42 进入监控室；临时值班员叶澜于 02:05 签退。",
    body: [
      "00:18　顾惟安　调度台签到",
      "00:42　周既明　监控室校时（手写补录）",
      "02:05　叶澜　档案室签退（无门禁编号）",
      "纸面右下角有一道旧压痕：00:31。手写补录与物理压痕并未对齐。",
      "页脚沿用‘无船靠泊’模板，第四栏同样写成‘泊 位’。压痕附近有多次擦写痕迹。",
    ],
    evidenceId: "ev-duty",
  },
  {
    id: "doc-port",
    code: "BERTH-7/RAW",
    title: "船只进港纸本记录",
    category: "航运记录",
    date: "2019.07.12",
    author: "夜班调度台",
    excerpt: "七号泊位无登记靠泊；纸纤维下仍可见 H-1707 的铅笔压痕。",
    body: [
      "00:20　闸门磁感器触发，船长 48.6 米，AIS 无响应。",
      "00:24　泊位称重板增加 12.1 吨；船方申报总载荷为 18.4 吨。",
      "01:07　外闸再次触发，泊位称重恢复原值。",
      "被擦除的船号只剩：H-17□7。调度员备注：‘白色维护船，临时靠泊。’",
      "事后录入栏写着‘泊 位无异常’，空格位置与结案摘要完全相同。",
    ],
    evidenceId: "ev-port-log",
  },
  {
    id: "doc-weather",
    code: "AWS-07/ORIGIN",
    title: "自动气象站原始日志",
    category: "传感器日志",
    date: "2019.07.12",
    author: "七码头 AWS-3",
    excerpt: "00:00—03:00 降水量 0.0 mm，能见度 1.8 km，轻雾。",
    body: [
      "00:10　气温 18.2℃ / 风速 2.1m/s / 降水 0.0mm",
      "00:31　岸钟反光校准帧写入 / 降水 0.0mm",
      "01:00　能见度 1.8km / 无雷暴回波",
      "02:17　降水 0.0mm。03:22 由许晚澄按上级口径补录‘暴雨警报’，同时将原始缓存留在只读节点。",
      "补录模板附注为‘泊 位无靠泊’，与另外三份事后材料保留同一处排版错误。",
    ],
    evidenceId: "ev-weather",
  },
  {
    id: "doc-phone",
    code: "TEL/00:39",
    title: "最后通话元数据",
    category: "通信记录",
    date: "2019.07.12",
    author: "雾港通信节点",
    excerpt: "00:39:12 拨往《海岸线》编辑唐芷，通话 02:38，并非家属号码。",
    body: [
      "主叫：林知夏工作终端 07-OBS-4",
      "被叫：唐芷 / 海岸线编辑部转接号",
      "开始：00:39:12　结束：00:41:50",
      "末尾录音被纸带机转存。背景中出现 A-17 报警节点的工作口令，以及一次明显的人为剪接。",
    ],
    evidenceId: "ev-phone",
  },
  {
    id: "doc-tape-analysis",
    code: "TAPE/A-17",
    title: "纸带剪接与报警节点分析",
    category: "声学取证",
    date: "当前会话",
    author: "纸带修复台",
    excerpt: "背景口令属于许晚澄的 A-17 节点；关闭动作发生在安保巡检抵达前。",
    body: [
      "纸带 02:31—02:34 存在一次非自然静音，磁粉边缘显示人为剪接而非介质老化。",
      "背景设备号 AWS-A17 绑定许晚澄。她在 00:40:06 远程关闭自动报警，最初看似在清除告警。",
      "巡检调度延后 126 秒。结合原始缓存可知，这次关闭为林知夏争取了离开气象站的时间。",
    ],
    unlockAfter: "frequency",
    evidenceId: "ev-tape-edit",
  },
  {
    id: "doc-clerk",
    code: "HR/TEMP-YL",
    title: "临时值班员：叶澜",
    category: "人事档案",
    date: "2019.07.13",
    author: "人事备份节点",
    excerpt: "只有姓名与当夜签退记录；身份、薪资、照片和纸质合同均为空。",
    body: [
      "档案创建：2019.07.13 03:04",
      "账号创建者：JM-ZHOU / 系统校时主管",
      "门禁卡序列：NULL　工资批次：NULL　证件影像：NULL",
      "该人员首次出现的时间，比所谓签退晚五十九分钟。",
    ],
    unlockAfter: "deduction",
    evidenceId: "ev-fake-clerk",
  },
  {
    id: "doc-manifest",
    code: "CARGO/H-1707",
    title: "白鹭七号货物复印件",
    category: "扣押附件",
    date: "2019.07.12",
    author: "澜汐航运",
    excerpt: "申报为‘盐度校准砝码’，实际卸下十二只铅封桶。",
    body: [
      "船号：H-1707 / 呼号：白鹭七号",
      "申报载荷：海洋观测设备 18.4 吨",
      "卸载：K-7 型铅封桶 12 只，实重 12.1 吨，去向栏盖有‘栖潮’圆章。",
      "内部检测附页：桶内为含汞声呐元件污泥。‘栖潮计划’借七处沿岸节点绕过危废申报，将其转入近海倾倒船。",
    ],
    unlockAfter: "deduction",
    evidenceId: "ev-manifest",
  },
  {
    id: "doc-payment-context",
    code: "AUDIT/GW-17",
    title: "异常付款与医院缴费单",
    category: "审计附件",
    date: "2019.07.12—07.16",
    author: "恢复的财务碎片",
    excerpt: "顾惟安关联账户收到款项前，女儿的急诊治疗已进入停缴倒计时。",
    body: [
      "00:16，儿科重症病区发送第三次欠费通知；治疗押金需在当日 06:00 前补齐。",
      "01:12，顾惟安的未发送语音：‘闸我开了，纸也擦了。别再碰我女儿。’",
      "07 月 16 日，澜汐航运关联账户补齐治疗款并另行转账。该记录说明胁迫背景，不撤销其协助与作伪责任。",
    ],
    unlockAfter: "deduction",
    evidenceId: "ev-medical-context",
  },
  {
    id: "doc-closure",
    code: "ORDER/0310",
    title: "内部结案与封存指令",
    category: "机密公文",
    date: "2019.07.12",
    author: "港务局联合办公室",
    excerpt: "03:10 已要求按‘暴雨落水’口径封存，而家属 04:25 才报案。",
    body: [
      "指令：P-07-0712 相关介质移交系统科统一校时后封存。",
      "天气口径：极端暴雨。船舶口径：七号泊位无靠泊。人员口径：实习员单独行动。",
      "签发时间：03:10。首次失踪报案入库时间：04:25。",
      "复核人栏被涂黑，透光后可见首字母 Z.J.M.。",
    ],
    unlockAfter: "deduction",
    evidenceId: "ev-closure-order",
  },
  {
    id: "doc-final",
    code: "ARCHIVE/FINAL",
    title: "最终档案：没有下雨的夜晚",
    category: "重建卷宗",
    date: "当前会话",
    author: "调查员 {{code}}",
    excerpt: "时间链、船号、虚构人员与封存指令已经闭合。",
    body: [
      "00:31，周既明进入监控室，将系统主时钟快调十一分钟，替白鹭七号制造不存在的时间缝隙。",
      "林知夏在 00:39 将证据告知唐芷，随后在外侧梯道遭拦截并坠海；陈牧暗中将她救起。",
      "叶澜从未存在。所谓暴雨、独自行动和无船靠泊，都是在事发后写入的同一套口径。",
      "H-1707 转运的十二只铅封桶装有含汞工业污泥；‘栖潮计划’借七处港口伪造天气与靠泊记录，掩护非法近海倾倒。",
      "会话审计显示：每次打开关键档案，都会有一个未登记的外部节点同步读取。潮汐_0 并不是唯一能看见调查进度的人。",
      "‘第七层’也许不是文件夹，而是一套仍在运行的监控与销毁机制。系统没有提供唯一答案。",
    ],
    unlockAfter: "deduction",
    evidenceId: "ev-final-chain",
  },
];

export const messages: CaseMessage[] = [
  {
    id: "msg-commission",
    from: "潮汐_0",
    subject: "委托：恢复 P-07-0712",
    time: "02:17",
    personal: true,
    body: [
      "{{code}}，七年前有人把一场无雨的夜晚写成了暴雨。",
      "不要先问我是谁。先找到第一个不肯服从屏幕的时钟。",
      "系统会记录你的每一步——因为我只能从这台备份节点看见你。",
    ],
  },
  {
    id: "msg-system",
    from: "档案系统",
    subject: "完整性校验失败",
    time: "02:18",
    body: ["检测到十一份卷宗、二十三项证物。部分索引被人为拆分。", "建议从案情摘要、签到表、进港记录、气象日志与通话元数据开始。"],
  },
  {
    id: "msg-offset",
    from: "潮汐_0",
    subject: "你找回了十一分钟",
    time: "02:29",
    unlockAfter: "schedule",
    body: ["现在去听纸带机。唐芷把声音藏在噪声上方，不在音量里。", "慢一点，高一点。数字不会主动向你开口。"],
  },
  {
    id: "msg-photo",
    from: "未登记转发节点",
    subject: "密封照片包 / 6 片",
    time: "02:41",
    unlockAfter: "frequency",
    body: ["口令 0712 已通过。照片在监控室的坏扫描仪里。", "拼好后别只看船，看看水里的第二个影子。"],
  },
  {
    id: "msg-tape",
    from: "无发件人",
    subject: "纸带并不是遗言",
    time: "02:42",
    unlockAfter: "frequency",
    body: ["录音带不是为了留下遗言，是为了让某个人知道她还活着。", "A-17 的关闭记录不能单独证明许晚澄在追捕她。先看动作造成了什么后果。"],
  },
  {
    id: "msg-reporter",
    from: "唐芷（草稿恢复）",
    subject: "没有下雨的溺亡夜",
    time: "00:57 / 七年前",
    unlockAfter: "photo",
    body: ["如果这封稿件能被读到，说明知夏说的船真的存在。她一开始并不信任我，我们是从另一宗污染调查才学会交换证据。", "她最后说：‘白鹭七号不是来避雨，它在卸货。’我删掉了会暴露她身份的地点；稿件准备发表后，我才失联。"],
  },
  {
    id: "msg-external-reader",
    from: "档案系统",
    subject: "检测到并发读取",
    time: "03:08",
    unlockAfter: "deduction",
    body: ["当前终端标记为离线，但关键卷宗每次打开时均出现第二读取游标。", "远端节点：ARCHIVE-02 / 身份未知 / 撤销失败。"],
  },
  {
    id: "msg-second-run",
    from: "无发件人",
    subject: "三次敲击",
    time: "本轮空闲记录",
    personal: true,
    body: ["咚。咚。咚。", "这一次，你比上次更快。"],
  },
  {
    id: "msg-trade",
    from: "潮汐_0",
    subject: "最后一次询问",
    time: "03:07",
    unlockAfter: "deduction",
    personal: true,
    body: ["{{code}}，你已经知道我为什么熟悉这宗案子。", "公开、删除，或继续向第七层走。你的选择会改变谁还能看见明天。"],
  },
];

export const audioRecords: AudioRecord[] = [
  {
    id: "audio-call",
    title: "纸带 A：最后通话",
    source: "唐芷编辑部备份",
    duration: "02:38",
    transcript: [
      "[00:08] 林知夏：不是暴雨……这里根本没下雨。",
      "[00:19] 林知夏：唐芷，我以前不信你。但我已经偷偷复制过一份，他们发现了。",
      "[00:41] 林知夏：船身是白的，编号被帆布挡住，只看见 H-17。",
      "[01:06] [背景口令] AWS-A17，远程关闭确认。操作员：许晚澄。",
      "[01:18] [背景] 三次金属敲击。远处男声：‘梯子放下。’",
      "[01:52] [高频脉冲] ----- --... .---- ..---",
      "[02:11] 林知夏：有人来了。把题目写成日期，他们会以为只是归档号。",
      "[02:34] [磁带剪接] 波形缺失 0.8 秒，切口为人工造成。",
    ],
    unlockAfter: "schedule",
  },
  {
    id: "audio-intercom",
    title: "纸带 B：监控室内线",
    source: "端口 3 缓存",
    duration: "00:46",
    transcript: [
      "[00:03] 顾惟安：岸钟还是三十一分，你那边为什么四十二？",
      "[00:09] 周既明：照新时间写。十一分钟足够把她和船拆进两个时间段。",
      "[00:18] 顾惟安：那值班的人名呢？",
      "[00:23] 周既明：写叶澜。别再问。",
    ],
    unlockAfter: "photo",
  },
  {
    id: "audio-anonymous",
    title: "纸带 C：匿名委托",
    source: "本次会话实时缓存",
    duration: "00:31",
    transcript: [
      "[00:04] 潮汐_0：陈牧把我从检修梯拉上来时，我以为所有证据都沉了。",
      "[00:12] 潮汐_0：七年后，系统还记得我的呼吸频率。",
      "[00:18] 潮汐_0：唐芷失踪时，稿件已经准备发表。她替我改掉了会暴露路线的三句话。",
      "[00:26] 潮汐_0：调查员，别再把我叫作失踪者。",
    ],
    unlockAfter: "deduction",
  },
];

export const timeline: TimelineEntry[] = [
  { id: "t-001", time: "00:09", title: "自动站记录轻雾", detail: "降水量 0.0mm，官方的暴雨尚不存在。", suspicious: true },
  { id: "t-002", time: "00:20", title: "七号闸门触发", detail: "无 AIS 船只进入，船长 48.6 米。" },
  { id: "t-003", time: "00:24", title: "十二只铅封桶卸下", detail: "称重板增加 12.1 吨，与申报总载荷 18.4 吨不符。" },
  { id: "t-004", time: "00:31", correctedTime: "系统记录 00:42", title: "周既明进入监控室", detail: "岸钟反光与电子时间相差十一分钟。", unlockAfter: "schedule", suspicious: true },
  { id: "t-005", time: "00:39", title: "林知夏拨给唐芷", detail: "通话 2 分 38 秒，并非家属号码。" },
  { id: "t-006", time: "00:43", title: "外侧通道出现争执", detail: "监控仅留下水面反光与两道人影。", unlockAfter: "photo" },
  { id: "t-007", time: "00:47", title: "检修梯报警被关闭", detail: "陈牧的工具箱留在下层梯道。", unlockAfter: "photo" },
  { id: "t-008", time: "01:07", title: "白鹭七号离港", detail: "载重减少 12.1 吨，船号 H-1707。", unlockAfter: "photo" },
  { id: "t-009", time: "03:04", title: "账号‘叶澜’被创建", detail: "创建时间晚于其虚构的签退记录。", unlockAfter: "deduction", suspicious: true },
  { id: "t-010", time: "03:10", title: "内部结案指令签发", detail: "比家属报案早七十五分钟。", unlockAfter: "deduction", suspicious: true },
  { id: "t-011", time: "04:25", title: "家属正式报案", detail: "此时档案已被按‘暴雨落水’口径封存。", unlockAfter: "deduction" },
];

export const locations: LocationRecord[] = [
  { id: "loc-archive", name: "旧档案馆", kind: "当前节点", x: 22, y: 24, description: "退役港务局资料楼。备份终端仍与七号泊位保留单向连接。", linkedEvidence: ["ev-case-file", "ev-fake-clerk"] },
  { id: "loc-control", name: "监控室", kind: "关键地点", x: 58, y: 31, description: "主时钟、录像与门禁在这里被统一校时。", linkedEvidence: ["ev-offset", "ev-cctv"] },
  { id: "loc-pier7", name: "第七码头", kind: "案发地点", x: 78, y: 57, description: "封锁泊位。外侧通道下方有一条只供维修艇使用的检修梯。", linkedEvidence: ["ev-photo", "ev-toolbox"] },
  { id: "loc-weather", name: "气象站 AWS-3", kind: "观测节点", x: 45, y: 66, description: "保留当夜无雨的只读缓存。", linkedEvidence: ["ev-weather", "ev-notebook"] },
  { id: "loc-gate", name: "七号外闸", kind: "航道", x: 89, y: 25, description: "磁感器先后在 00:20 与 01:07 触发。", linkedEvidence: ["ev-port-log", "ev-manifest"] },
];

export const endings: Record<string, CaseEnding> = {
  truth: {
    id: "truth",
    label: "公开全部档案",
    kicker: "结局 A / 公布真相",
    title: "雾散以前",
    body: [
      "{{code}} 将重建档案、原始气象日志与 H-1707 货单同步发送给七家媒体。十二小时后，案件宣布重启。",
      "周既明与雾港栖潮节点曝光；顾惟安、许晚澄和陈牧的责任被拆开呈现。林知夏的生还路线也开始面临暴露。",
      "上传完成后收到一条只写着‘我看到了’的消息。来源既像潮汐_0，也像那个同步读取档案的外部节点。",
    ],
  },
  trade: {
    id: "trade",
    label: "接受匿名交易",
    kicker: "结局 B / 接受交易",
    title: "被删除的人",
    body: [
      "{{code}} 与潮汐_0 达成有限公开：污染、靠泊与作伪证据被送出，林知夏的生还路径被隐藏。",
      "顾惟安的胁迫、许晚澄的双重行为与陈牧的保护性隐瞒被分层呈现，没有人因此被自动洗白。",
      "清晨 04:12，一份档案显示已删除；同一秒，ARCHIVE-02 自动生成了另一份副本。",
    ],
  },
  seventh: {
    id: "seventh",
    label: "进入隐藏档案",
    kicker: "结局 C / 档案第七码头",
    title: "第七层以下",
    body: [
      "{{code}} 没有公开，也没有删除。你用镜像口令继续追踪栖潮计划其余六个港口节点。",
      "终端忽然显示：‘调查员档案已创建。’最后一页写入你的代号、进入时间与本轮操作摘要。",
      "新的终端亮起：ARCHIVE 02 / 潮位正在上升。你仍在调查，也已经成为被归档的对象。",
    ],
  },
};

export const puzzleGuidance = {
  schedule: ["先读完四份具有时间戳的记录。", "物理传感器与自动站不会一起说谎。", "比较 00:31 与手写补录的时间。"],
  frequency: ["密码不只取决于输入内容。", "让速度慢下来，并保留较高频率。", "目标在纸带的后半段，摩斯码表示案件日期。"],
  photo: ["碎片必须回到正确位置。", "船身横线和岸灯倒影可以跨越碎片边缘。", "拼合后仍需主动确认船号与水线附近的异常，逐区扫描只负责缩小范围。"],
  deduction: ["先自由尝试分类，提交后系统才会统一报告错误类型。", "从拥有主时钟权限的人开始。", "目的不是掩盖落水，而是掩盖一艘船的靠泊。"],
  hidden: ["地图背面有一行镜像字符。", "先把 7EDIT 翻转，再按正常顺序输入。", "口令由英文潮汐与数字七组成。"],
};
