import type {
  ArchiveDocument,
  AudioRecord,
  CaseEnding,
  CaseMessage,
  LocationRecord,
  Person,
  TimelineEntry,
} from "@/types/case";

export const CASE_NUMBER = "P-07-0712";
export const INCIDENT_DATE = "2019.07.12";

export const people: Person[] = [
  {
    id: "lin-zhixia",
    name: "林知夏",
    role: "港口气象观测站实习员",
    ageAtIncident: 21,
    status: "失踪 / 法定状态不明",
    summary: "最后被记录于第七码头外侧通道。官方称她在暴雨中落水，但自动站没有记录到降雨。",
    statement: "她没有留下正式证词。笔记边缘反复写着：‘不要相信屏幕上的时间。’",
    linkedEvidence: ["ev-case-file", "ev-weather", "ev-phone", "ev-notebook"],
    secret: "她被陈牧从检修梯救起，此后以匿名委托人的身份追查栖潮计划。",
  },
  {
    id: "zhou-jiming",
    name: "周既明",
    role: "港务系统校时主管",
    ageAtIncident: 44,
    status: "三年前离职 / 去向不明",
    summary: "案发当夜拥有监控室和主时钟双重权限，是唯一能同时修改签到与录像时间的人。",
    statement: "‘零点以后我一直在北楼。那晚雨大，谁也没必要靠近七号泊位。’",
    linkedEvidence: ["ev-duty", "ev-offset", "ev-cctv", "ev-payment"],
    secret: "接受澜汐航运付款，将监控时间整体快调十一分钟，并补写不存在的值班员。",
  },
  {
    id: "gu-weian",
    name: "顾惟安",
    role: "夜班调度员",
    ageAtIncident: 38,
    status: "仍在港务局任职",
    summary: "负责泊位闸门。他坚持当夜没有船只进入第七码头，却在纸本日志上留下了被擦除的压痕。",
    statement: "‘七号泊位封着。汽笛来自外海，我没看见白色船身。’",
    linkedEvidence: ["ev-port-log", "ev-photo", "ev-manifest"],
    secret: "按周既明指令打开闸门，事后以女儿医药费名义收到封口款。",
  },
  {
    id: "xu-wancheng",
    name: "许晚澄",
    role: "气象站值班工程师",
    ageAtIncident: 31,
    status: "调任外港观测站",
    summary: "林知夏的带教。她签署了‘极端暴雨’补录单，却拒绝删除自动站原始缓存。",
    statement: "‘我按上级口径补录天气。原始仪器有没有故障，我不能断言。’",
    linkedEvidence: ["ev-weather", "ev-closure-order", "ev-notebook"],
    secret: "她保留了无雨原始日志，暗中给林知夏留下了逃生时间。",
  },
  {
    id: "chen-mu",
    name: "陈牧",
    role: "拖轮维修工",
    ageAtIncident: 52,
    status: "2020 年海上事故死亡",
    summary: "当夜值守检修艇。他的工具箱在七号泊位下层梯道被找到，证词却称自己从未离开船坞。",
    statement: "‘我只听见一声落水，雾太重，没看清人。’",
    linkedEvidence: ["ev-toolbox", "ev-photo", "ev-audio-0712"],
    secret: "从检修梯救起林知夏，并用物料艇把她送出港区。",
  },
  {
    id: "tang-zhi",
    name: "唐芷",
    role: "《海岸线》调查记者",
    ageAtIncident: 29,
    status: "停刊后失联",
    summary: "林知夏最后一通电话的真实接听人。通话后四小时，她的编辑部硬盘被没收。",
    statement: "未留正式证词。未寄出的稿件标题是《没有下雨的溺亡夜》。",
    linkedEvidence: ["ev-phone", "ev-audio-0712", "ev-draft"],
    secret: "她将通话备份藏进旧式录音带，以摩斯码标注案件编号。",
  },
  {
    id: "ye-lan",
    name: "叶澜",
    role: "档案记录中的临时值班员",
    ageAtIncident: 0,
    status: "查无此人",
    summary: "没有身份证号、工资记录或门禁卡实体，签名笔迹与周既明的校时单一致。",
    statement: "档案中只有一句事后代录：‘00:54，暴雨，实习员独自向外侧通道移动。’",
    linkedEvidence: ["ev-fake-clerk", "ev-duty", "ev-cctv"],
    secret: "周既明为封闭时间链而创建的虚构身份。",
  },
];

export const archiveDocuments: ArchiveDocument[] = [
  {
    id: "doc-case",
    code: "P-07-0712/A",
    title: "失踪事件结案摘要",
    category: "案情卷宗",
    date: "2019.07.16",
    author: "雾港港务局安保处",
    excerpt: "实习员于极端暴雨期间擅入封锁区域，推定夜间落水。",
    body: [
      "失踪者：林知夏，女，21 岁，气象观测站实习员。",
      "记录称 00:54 监控拍到其独自进入第七码头外侧通道。01:00 画面中断。",
      "搜救持续三十六小时，未发现遗体。鉴于当夜极端暴雨、海况恶劣，事件定性为意外落水。",
      "附注：所有涉及七号泊位的船舶记录不属于本案调查范围。",
    ],
    evidenceId: "ev-case-file",
    secondRunNote: "二周目新增铅笔字：‘我看到你第二次打开它了，{{code}}。——知夏’",
  },
  {
    id: "doc-duty",
    code: "NIGHT/07-12",
    title: "夜班签到与校时表",
    category: "行政记录",
    date: "2019.07.12",
    author: "港务系统科",
    excerpt: "周既明于 00:42 进入监控室；临时值班员叶澜于 02:05 签退。",
    body: [
      "00:18　顾惟安　调度台签到",
      "00:42　周既明　监控室校时（手写补录）",
      "02:05　叶澜　档案室签退（无门禁编号）",
      "纸面右下角有一道旧压痕：00:31。手写补录与物理压痕并未对齐。",
    ],
    evidenceId: "ev-duty",
  },
  {
    id: "doc-port",
    code: "BERTH-7/RAW",
    title: "船只进港纸本记录",
    category: "航运记录",
    date: "2019.07.12",
    author: "夜班调度台",
    excerpt: "七号泊位无登记靠泊；纸纤维下仍可见 H-1707 的铅笔压痕。",
    body: [
      "00:20　闸门磁感器触发，船长 48.6 米，AIS 无响应。",
      "00:24　泊位称重板增加 12.1 吨；船方申报总载荷为 18.4 吨。",
      "01:07　外闸再次触发，泊位称重恢复原值。",
      "被擦除的船号只剩：H-17□7。调度员备注：‘白色维护船，临时靠泊。’",
    ],
    evidenceId: "ev-port-log",
  },
  {
    id: "doc-weather",
    code: "AWS-07/ORIGIN",
    title: "自动气象站原始日志",
    category: "传感器日志",
    date: "2019.07.12",
    author: "七码头 AWS-3",
    excerpt: "00:00—03:00 降水量 0.0 mm，能见度 1.8 km，轻雾。",
    body: [
      "00:10　气温 18.2℃ / 风速 2.1m/s / 降水 0.0mm",
      "00:31　岸钟反光校准帧写入 / 降水 0.0mm",
      "01:00　能见度 1.8km / 无雷暴回波",
      "02:17　降水 0.0mm。03:22 由许晚澄按上级口径补录‘暴雨警报’，同时将原始缓存留在只读节点。",
    ],
    evidenceId: "ev-weather",
  },
  {
    id: "doc-phone",
    code: "TEL/00:39",
    title: "最后通话元数据",
    category: "通信记录",
    date: "2019.07.12",
    author: "雾港通信节点",
    excerpt: "00:39:12 拨往《海岸线》编辑唐芷，通话 02:38，并非家属号码。",
    body: [
      "主叫：林知夏工作终端 07-OBS-4",
      "被叫：唐芷 / 海岸线编辑部转接号",
      "开始：00:39:12　结束：00:41:50",
      "末尾录音被纸带机转存。背景中出现三短、一长的港内汽笛。",
    ],
    evidenceId: "ev-phone",
  },
  {
    id: "doc-clerk",
    code: "HR/TEMP-YL",
    title: "临时值班员：叶澜",
    category: "人事档案",
    date: "2019.07.13",
    author: "人事备份节点",
    excerpt: "只有姓名与当夜签退记录；身份、薪资、照片和纸质合同均为空。",
    body: [
      "档案创建：2019.07.13 03:04",
      "账号创建者：JM-ZHOU / 系统校时主管",
      "门禁卡序列：NULL　工资批次：NULL　证件影像：NULL",
      "该人员首次出现的时间，比所谓签退晚五十九分钟。",
    ],
    unlockAfter: "deduction",
    evidenceId: "ev-fake-clerk",
  },
  {
    id: "doc-manifest",
    code: "CARGO/H-1707",
    title: "白鹭七号货物复印件",
    category: "扣押附件",
    date: "2019.07.12",
    author: "澜汐航运",
    excerpt: "申报为‘盐度校准砝码’，实际卸下十二只铅封桶。",
    body: [
      "船号：H-1707 / 呼号：白鹭七号",
      "申报载荷：海洋观测设备 18.4 吨",
      "卸载：K-7 型铅封桶 12 只，实重 12.1 吨，去向栏盖有‘栖潮’圆章。",
      "内部检测附页：桶内为含汞声呐元件污泥。‘栖潮计划’借七处沿岸节点绕过危废申报，将其转入近海倾倒船。",
    ],
    unlockAfter: "deduction",
    evidenceId: "ev-manifest",
  },
  {
    id: "doc-closure",
    code: "ORDER/0310",
    title: "内部结案与封存指令",
    category: "机密公文",
    date: "2019.07.12",
    author: "港务局联合办公室",
    excerpt: "03:10 已要求按‘暴雨落水’口径封存，而家属 04:25 才报案。",
    body: [
      "指令：P-07-0712 相关介质移交系统科统一校时后封存。",
      "天气口径：极端暴雨。船舶口径：七号泊位无靠泊。人员口径：实习员单独行动。",
      "签发时间：03:10。首次失踪报案入库时间：04:25。",
      "复核人栏被涂黑，透光后可见首字母 Z.J.M.。",
    ],
    unlockAfter: "deduction",
    evidenceId: "ev-closure-order",
  },
  {
    id: "doc-final",
    code: "ARCHIVE/FINAL",
    title: "最终档案：没有下雨的夜晚",
    category: "重建卷宗",
    date: "当前会话",
    author: "调查员 {{code}}",
    excerpt: "时间链、船号、虚构人员与封存指令已经闭合。",
    body: [
      "00:31，周既明进入监控室，将系统主时钟快调十一分钟，替白鹭七号制造不存在的时间缝隙。",
      "林知夏在 00:39 将证据告知唐芷，随后在外侧梯道遭拦截并坠海；陈牧暗中将她救起。",
      "叶澜从未存在。所谓暴雨、独自行动和无船靠泊，都是在事发后写入的同一套口径。",
      "H-1707 转运的十二只铅封桶装有含汞工业污泥；‘栖潮计划’借七处港口伪造天气与靠泊记录，掩护非法近海倾倒。",
    ],
    unlockAfter: "deduction",
    evidenceId: "ev-final-chain",
  },
];

export const messages: CaseMessage[] = [
  {
    id: "msg-commission",
    from: "潮汐_0",
    subject: "委托：恢复 P-07-0712",
    time: "02:17",
    personal: true,
    body: [
      "{{code}}，七年前有人把一场无雨的夜晚写成了暴雨。",
      "不要先问我是谁。把四份时间记录放在一起，找到那段被偷走的分钟。",
      "系统会记录你的每一步——因为我只能从这台备份节点看见你。",
    ],
  },
  {
    id: "msg-system",
    from: "档案系统",
    subject: "完整性校验失败",
    time: "02:18",
    body: ["检测到九份卷宗、十九项证物。部分索引被人为拆分。", "建议从案情摘要、签到表、进港记录、气象日志与通话元数据开始。"],
  },
  {
    id: "msg-offset",
    from: "潮汐_0",
    subject: "你找回了十一分钟",
    time: "02:29",
    unlockAfter: "schedule",
    body: ["现在去听纸带机。唐芷把声音藏在噪声上方，不在音量里。", "慢一点，高一点。数字不会主动向你开口。"],
  },
  {
    id: "msg-photo",
    from: "未登记转发节点",
    subject: "密封照片包 / 6 片",
    time: "02:41",
    unlockAfter: "frequency",
    body: ["口令 0712 已通过。照片在监控室的坏扫描仪里。", "拼好后别只看船，看看水里的第二个影子。"],
  },
  {
    id: "msg-reporter",
    from: "唐芷（草稿恢复）",
    subject: "没有下雨的溺亡夜",
    time: "00:57 / 七年前",
    unlockAfter: "photo",
    body: ["如果这封稿件能被读到，说明知夏说的船真的存在。", "她最后说：‘白鹭七号不是来避雨，它在卸货。’"],
  },
  {
    id: "msg-trade",
    from: "潮汐_0",
    subject: "最后一次询问",
    time: "03:07",
    unlockAfter: "deduction",
    personal: true,
    body: ["{{code}}，你已经知道我为什么熟悉这宗案子。", "公开、删除，或继续向第七层走。你的选择会改变谁还能看见明天。"],
  },
];

export const audioRecords: AudioRecord[] = [
  {
    id: "audio-call",
    title: "纸带 A：最后通话",
    source: "唐芷编辑部备份",
    duration: "02:38",
    transcript: [
      "[00:08] 林知夏：不是暴雨……这里根本没下雨。",
      "[00:41] 林知夏：船身是白的，编号被帆布挡住，只看见 H-17。",
      "[01:52] [高频脉冲] ----- --... .---- ..---",
      "[02:11] 林知夏：有人来了。把题目写成日期，他们会以为只是归档号。",
    ],
    unlockAfter: "schedule",
  },
  {
    id: "audio-intercom",
    title: "纸带 B：监控室内线",
    source: "端口 3 缓存",
    duration: "00:46",
    transcript: [
      "[00:03] 顾惟安：岸钟还是三十一分，你那边为什么四十二？",
      "[00:09] 周既明：照新时间写。十一分钟足够把她和船拆进两个时间段。",
      "[00:18] 顾惟安：那值班的人名呢？",
      "[00:23] 周既明：写叶澜。别再问。",
    ],
    unlockAfter: "photo",
  },
  {
    id: "audio-anonymous",
    title: "纸带 C：匿名委托",
    source: "本次会话实时缓存",
    duration: "00:31",
    transcript: [
      "[00:04] 潮汐_0：陈牧把我从检修梯拉上来时，我以为所有证据都沉了。",
      "[00:12] 潮汐_0：七年后，系统还记得我的呼吸频率。",
      "[00:26] 潮汐_0：调查员，别再把我叫作失踪者。",
    ],
    unlockAfter: "deduction",
  },
];

export const timeline: TimelineEntry[] = [
  { id: "t-001", time: "00:09", title: "自动站记录轻雾", detail: "降水量 0.0mm，官方的暴雨尚不存在。", suspicious: true },
  { id: "t-002", time: "00:20", title: "七号闸门触发", detail: "无 AIS 船只进入，船长 48.6 米。" },
  { id: "t-003", time: "00:24", title: "十二只铅封桶卸下", detail: "称重板增加 12.1 吨，与申报总载荷 18.4 吨不符。" },
  { id: "t-004", time: "00:31", correctedTime: "系统记录 00:42", title: "周既明进入监控室", detail: "岸钟反光与电子时间相差十一分钟。", unlockAfter: "schedule", suspicious: true },
  { id: "t-005", time: "00:39", title: "林知夏拨给唐芷", detail: "通话 2 分 38 秒，并非家属号码。" },
  { id: "t-006", time: "00:43", title: "外侧通道出现争执", detail: "监控仅留下水面反光与两道人影。", unlockAfter: "photo" },
  { id: "t-007", time: "00:47", title: "检修梯报警被关闭", detail: "陈牧的工具箱留在下层梯道。", unlockAfter: "photo" },
  { id: "t-008", time: "01:07", title: "白鹭七号离港", detail: "载重减少 12.1 吨，船号 H-1707。", unlockAfter: "photo" },
  { id: "t-009", time: "03:04", title: "账号‘叶澜’被创建", detail: "创建时间晚于其虚构的签退记录。", unlockAfter: "deduction", suspicious: true },
  { id: "t-010", time: "03:10", title: "内部结案指令签发", detail: "比家属报案早七十五分钟。", unlockAfter: "deduction", suspicious: true },
  { id: "t-011", time: "04:25", title: "家属正式报案", detail: "此时档案已被按‘暴雨落水’口径封存。", unlockAfter: "deduction" },
];

export const locations: LocationRecord[] = [
  { id: "loc-archive", name: "旧档案馆", kind: "当前节点", x: 22, y: 24, description: "退役港务局资料楼。备份终端仍与七号泊位保留单向连接。", linkedEvidence: ["ev-case-file", "ev-fake-clerk"] },
  { id: "loc-control", name: "监控室", kind: "关键地点", x: 58, y: 31, description: "主时钟、录像与门禁在这里被统一校时。", linkedEvidence: ["ev-offset", "ev-cctv"] },
  { id: "loc-pier7", name: "第七码头", kind: "案发地点", x: 78, y: 57, description: "封锁泊位。外侧通道下方有一条只供维修艇使用的检修梯。", linkedEvidence: ["ev-photo", "ev-toolbox"] },
  { id: "loc-weather", name: "气象站 AWS-3", kind: "观测节点", x: 45, y: 66, description: "保留当夜无雨的只读缓存。", linkedEvidence: ["ev-weather", "ev-notebook"] },
  { id: "loc-gate", name: "七号外闸", kind: "航道", x: 89, y: 25, description: "磁感器先后在 00:20 与 01:07 触发。", linkedEvidence: ["ev-port-log", "ev-manifest"] },
];

export const endings: Record<string, CaseEnding> = {
  truth: {
    id: "truth",
    label: "公开全部档案",
    kicker: "结局 A / 公布真相",
    title: "雾散以前",
    body: [
      "{{code}} 将重建档案、原始气象日志与 H-1707 货单同步发送给七家媒体。十二小时后，案件宣布重启。",
      "周既明的住址已经空了，顾惟安没有出现在第二天的班表上。海岸线上第一次有人公开说：那晚没有下雨。",
      "匿名节点在上传完成前自行熔断，只留下六个字：‘谢谢你相信时间。’",
    ],
  },
  trade: {
    id: "trade",
    label: "接受匿名交易",
    kicker: "结局 B / 接受交易",
    title: "被删除的人",
    body: [
      "{{code}} 删除了可公开验证的档案。作为交换，潮汐_0 发送来一份从未存在于户籍系统的童年记录。",
      "记录显示你曾在‘栖潮计划’的另一座港口被登记为观察对象。关于林知夏的真相再次沉入离线节点。",
      "清晨 04:12，所有窗口关闭。桌面上只剩一张写着你旧名字的湿纸条。",
    ],
  },
  seventh: {
    id: "seventh",
    label: "进入隐藏档案",
    kicker: "结局 C / 档案第七码头",
    title: "第七层以下",
    body: [
      "{{code}} 没有公开，也没有删除。你用镜像口令打开了地图背面的第七层索引。",
      "雾港不是起点。H-1707 在七年间停靠过七座沿岸城市，每一座都留下一个被改写的夜晚。",
      "新的终端亮起：ARCHIVE 02 / 潮位正在上升。潮汐_0 第一次用自己的名字向你问好——林知夏。",
    ],
  },
};

export const puzzleGuidance = {
  schedule: ["先读完四份具有时间戳的记录。", "物理传感器与自动站不会一起说谎。", "比较 00:31 与手写补录的时间。"],
  frequency: ["密码不只取决于输入内容。", "让速度慢下来，并保留较高频率。", "目标在纸带的后半段，摩斯码表示案件日期。"],
  photo: ["碎片必须在正确位置且方向一致。", "船身横线和岸灯倒影可以跨越碎片边缘。", "每片都能用旋转按钮恢复至 0°。"],
  deduction: ["每个槽位只接受同类线索。", "从拥有主时钟权限的人开始。", "目的不是掩盖落水，而是掩盖一艘船的靠泊。"],
  hidden: ["地图背面有一行镜像字符。", "先把 7EDIT 翻转，再按正常顺序输入。", "口令由英文潮汐与数字七组成。"],
};
